---
name: Docker
on: push
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      -
        uses: ruby/setup-ruby@v1
      -
        name: Build the Docker image
        run: rake docker:build
...
