---
name: Test
on: push
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      -
        uses: ruby/setup-ruby@v1
      -
        uses: oprypin/install-crystal@v1
      -
        name: Run tests
        run: rake test
...
