---
name: Test
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v4
      -
        uses: ruby/setup-ruby@v1
      -
        uses: crystal-lang/install-crystal@v1
      -
        name: Run tests
        run: rake test
  lint:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v4
      -
        uses: ruby/setup-ruby@v1
      -
        uses: crystal-lang/install-crystal@v1
      -
        name: Run tests
        run: rake fmt:check
...
